name: terraform Actions Demo
on: 
  push:
    branches:
      - main

jobs: 
  run-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: create infra test
      - uses: actions/checkout@v3
      - shell: bash
      - env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd aws-infra
          terraform init
          terraform validate
          terraform apply --auto-approve
          terraform destroy --auto-approve