name: terraform Actions Demo
on: 
  push:
    branches:
      - main

jobs: 
  run-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create infra  
        run: |
          cd aws-infra
          terraform init
          terraform validate
#          terraform apply --auto-approve
          ls -la
#          terraform destroy --auto-approve