name: Terraform GitHub Actions Test
on: 
  push: 
    branches: 
      - main

jobs: 
  run-terraform-test: 
    name: Run Terraform Test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        shell: bash
        uses: actions/checkout@v3
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd aws-infra
        - name: Init
          terraform init
        - name: Validate
          terraform validate
        - name: Apply
          terraform apply --auto-approve
        - name: Destroy
          terraform destroy --auto-approve