name: Terraform GitHub Actions Test
on: 
  push: 
    branches: 
      - main

jobs: 
  run-terraform-test: 
    name: Run Terraform Test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
      - uses: actions/checkout@v3

    steps: 
      - name: Init
      - shell: bash
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd aws-infra
          terraform init

    steps: 
      - name: Validate
      - shell: bash
        run: |
          cd aws-infra
          terraform validate

    steps: 
      - name: Apply
      - shell: bash
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd aws-infra
          terraform apply --auto-approve

    steps: 
      - name: Destroy
      - shell: bash
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd aws-infra
          terraform destroy --auto-approve