name: Terraform GitHub Actions Test
on: 
  push: 
    branches: 
      - main

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs: 
  run-terraform-test: 
    name: Run Terraform Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./aws-infra
    steps: 
    - uses: actions/checkout@v3
      name: GitHub Checkout
    - name: Terraform Init
      run: terraform init
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Apply
      run: terraform apply --auto-approve
    - name: Terraform Destroy
      run: terraform destroy --auto-approve